export const colorVarMap = {
	bg: '--color-bg',
	bgSubtle: '--color-bg-subtle',
	bgMuted: '--color-bg-muted',
	surface: '--color-surface',
	surfaceRaised: '--color-surface-raised',
	border: '--color-border',
	borderStrong: '--color-border-strong',
	text: '--color-text',
	textMuted: '--color-text-muted',
	textSubtle: '--color-text-subtle',
	textInverse: '--color-text-inverse',
	primary: '--color-primary',
	primaryHover: '--color-primary-hover',
	primaryActive: '--color-primary-active',
	primarySubtle: '--color-primary-subtle',
	success: '--color-success',
	successWeak: '--color-success-weak',
	successText: '--color-success-text',
	warning: '--color-warning',
	warningWeak: '--color-warning-weak',
	warningText: '--color-warning-text',
	error: '--color-error',
	errorWeak: '--color-error-weak',
	errorText: '--color-error-text',
	errorRing: '--color-error-ring',
	info: '--color-info',
	infoWeak: '--color-info-weak',
	infoText: '--color-info-text',
	overlay: '--color-overlay',
} as const;

export const shadowVarMap = {
	sm: '--shadow-sm',
	base: '--shadow-base',
	md: '--shadow-md',
	lg: '--shadow-lg',
	xl: '--shadow-xl',
	inner: '--shadow-inner',
	fieldShell: '--shadow-field-shell',
	fieldFocus: '--shadow-field-focus',
	buttonPrimary: '--shadow-button-primary',
	buttonPrimaryHover: '--shadow-button-primary-hover',
	buttonPrimaryActive: '--shadow-button-primary-active',
	buttonSecondaryHover: '--shadow-button-secondary-hover',
} as const;

export const typographyVarMap = {
	fontFamilySans: '--font-family-sans',
	fontFamilyMono: '--font-family-mono',
	fontCaption: '--font-caption',
	fontSm: '--font-sm',
	fontSmRelaxed: '--font-sm-relaxed',
	fontBase: '--font-base',
	fontLgRelaxed: '--font-lg-relaxed',
	fontLabel: '--font-label',
	fontControl: '--font-control',
	fontControlLg: '--font-control-lg',
	fontStrongSm: '--font-strong-sm',
	fontTitle: '--font-title',
	fontWeightMedium: '--font-weight-medium',
	fontWeightBold: '--font-weight-bold',
	letterSpacingTight: '--letter-spacing-tight',
	letterSpacingSnug: '--letter-spacing-snug',
	letterSpacingNormal: '--letter-spacing-normal',
	letterSpacingWide: '--letter-spacing-wide',
	letterSpacingWider: '--letter-spacing-wider',
	letterSpacingWidest: '--letter-spacing-widest',
} as const;

export const zIndexVarMap = {
	overlay: '--z-index-overlay',
	floating: '--z-index-floating',
	toast: '--z-index-toast',
} as const;
